### ISSUE TITLE
Script stuck when running in Dockerfile as RUN

### ISSUE THREAD

**Issue by vldmarton** [gdraheim/docker-systemctl-replacement#101]
Hello,
first of all - thanks for this great script!

I'm trying to use it inside Dockerfile so that the container is started with sshd up and running. What I'm doing is:
`RUN python systemctl.py start sshd`

The output:
`08:11:39  ---> Running in c0f71bf830a7`
`08:11:46 sshd.service: `

And it just hangs there, nothing is going on. (Waited for about 10 minutes). If I do this step manually in the container after it was started, it succeeds without any problem. Am I doing something wrong?

**Comment by gdraheim** [comment]
Hello,

there are a couple of examples using Dockerfile for provisioning.
Please have a look at https://github.com/gdraheim/docker-systemctl-images
