### ISSUE TITLE
Bash scripts unable to run on certain systems due to shebang

### ISSUE THREAD

**Issue by Atchuu** [gdraheim/docker-systemctl-replacement#102]
I tried to use your script on our RHEL 7 based docker images, but ran into a problem that I believe is a simple fix.

The shebang (`#!`) in the systemctl scripts have hard coded paths for python and python3. The problem comes when you use the RH shipped versions of Python3, which involves setting up system similar to virtualenv using the SCL library. What that effectively does, it is places the fully python3 install into a location that is buried into a special location on the system, and your python executable ends up being on a path similar to (on RHEL 7 using scl:) `/opt/rh/rh-python3X/root/usr/bin/python3`.

I believe it's generally considered good practice to use `/usr/bin/env <executable>` to dynamically load the interpreter you want via the path. So I changed the python2 script as well, for consistency.

A pull request will quickly follow.

**Comment by gdraheim** [comment]
I do understand what you want to achieve but I do not like the approach. The systemctl.py is implemented in Python but it does not need a new version. In an RHEL7 you can just use the standard python2 interpreter.

https://github.com/gdraheim/docker-systemctl-images/blob/develop/centos7-postgres.dockerfile

There is a different solution to replace the interpreter path in the systemctl.py script when installing the file into the container. I have started to use that when moving my software to CentOs8 images lately where Python3 is pre-installed but it is not visible in the /usr/bin path.

Have a look here: https://github.com/gdraheim/docker-systemctl-images/blob/develop/centos8-postgres.dockerfile
