### ISSUE TITLE
Include your script in WSL distros Fedora Remix and Pengwin

### ISSUE THREAD

**Issue by crramirez** [gdraheim/docker-systemctl-replacement#106]
Hello, 

Your script is a perfect fit to provide syatemd to Fedora Remix in WSL due to its service command is based on systemd, and it is not supported in WSL.

I want to include it as part of the distribution Fedora Remix and Pengwin. Both are opensource and also sold in Microsoft Store. 

I don't understand well if I can use them because I don't know the EU license, and it has a clause that cannot be used for a different purpose that is made for. And I won't use it with docker.

Regards,
Carlos

**Comment by gdraheim** [comment]
Hello Carlos,

the EUPL has a list of compatible licenses that the source code may be even relabelled with. It should be fine with Fedora which I think is GPL.

I don't know about Pengwin though and what it is about to be sold in the Microsoft Store. Surely, I have investend hundreds of hours so far, so that I would like to know where it goes.

**Comment by gdraheim** [comment]
Closing a month later. I hope that the explanations helped to do the inclusion.

**Comment by crramirez** [comment]
Hello Guido,

I am really sorry for the late response I was full with other things and I forgot to answer. The projects are as follows:

**Fedora Remix for WSL**
https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL
License: https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/blob/master/LICENSE.md
Microsoft Store: https://www.microsoft.com/en-us/p/fedora-remix-for-wsl/9n6gdm4k2hnc

**Pengwin**
https://github.com/WhitewaterFoundry/Pengwin
License: https://github.com/WhitewaterFoundry/Pengwin/blob/master/LICENSE.md
Microsoft Store: https://www.microsoft.com/en-us/p/pengwin/9nv1gv1pxz6p

Both are open source projects Fedora Remix based on Fedora and Pengwin based on Debian. And we also sell them in Microsoft Store to finance our development.

Your component, name, and license would be included in the LICENSE.md file for both projects.

Regards,
Carlos

**Comment by crramirez** [comment]
If you want to see your script in action in WSL please attend to the WSLMicro conf: https://www.wslconf.dev/ in my presentation I will show it

**Comment by gdraheim** [comment]
Thanks a lot, I am quite busy in my day job lateley but I had the chance to have a quick look just now. I found your talk at

https://www.facebook.com/ubuntulinux/videos/371353423860863

I wish you all the best and keep up the good work.

**Comment by crramirez** [comment]
Excellent that you saw it, and thank you very much. This recording has some lag. The following is a new more accurate recording: https://youtu.be/hmMRFV1Koyo?t=1252 also I shared in the time when I begin to talk about the problem that your project solves.

I also during the conference, received the comment tha someone will try this solution on Clear Linux.

Good job
