### ISSUE TITLE
No PIDFile for forking '/etc/init.d/supervisord'

### ISSUE THREAD

**Issue by jfoliveira** [gdraheim/docker-systemctl-replacement#107]
I'm trying to install/restart/test supervisord in a container running the systemctl replacement and the logs say there is no PIDFile for forking.

Where/which systemctl replacement log files other than `/var/log/systemctl.debug.log` I could look at for further details?
Is this an issue with supervisord service itself or with my usage of systemctl replacement?

**Output - systemctl start supervisord**
```shell
$ touch /var/log/systemctl.debug.log 

$ systemctl start supervisord
INFO:systemctl:EXEC BEGIN /usr/bin/systemctl start supervisord --system
DEBUG:systemctl:======= systemctl.py start supervisord
DEBUG:systemctl:found 22 sysd files
DEBUG:systemctl:found 14 sysv files
INFO:systemctl:system is offline
DEBUG:systemctl:'/etc/init.d/supervisord' no --user mode >> accept
DEBUG:systemctl: start unit supervisord.service => '/etc/init.d/supervisord'
DEBUG:systemctl:extra-vars []
INFO:systemctl:forking start '/etc/init.d/supervisord' 'start'
INFO:systemctl:forking started PID 26633
INFO:systemctl:forking stopped PID 26633 (1) <->
WARNING:systemctl:No PIDFile for forking '/etc/init.d/supervisord'
DEBUG:systemctl:writing to /run/supervisord.service.status
	ActiveState=failed
DEBUG:systemctl:writing to /run/supervisord.service.status
	ExecMainCode=1
WARNING:systemctl:forking start not active
```

**Output - systemctl status supervisord**
```shell
$ systemctl status supervisord
INFO:systemctl:EXEC BEGIN /usr/bin/systemctl status supervisord --system
DEBUG:systemctl:======= systemctl.py status supervisord
DEBUG:systemctl:found 22 sysd files
DEBUG:systemctl:found 14 sysv files
supervisord.service - Start/stop supervisor daemon and its configured
    Loaded: loaded (/etc/init.d/supervisord, disabled)
    Active: failed (dead)
```

**My docker file:**
```dockerfile
FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    dbus \
    python3 \
    openssh-server

RUN curl -o ./systemctl3.py https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/v1.5.4260/files/docker/systemctl3.py
RUN mv systemctl3.py /usr/bin/systemctl
RUN chmod +x /usr/bin/systemctl
RUN test -L /bin/systemctl || ln -sf /usr/bin/systemctl /bin/systemctl

CMD ["/usr/bin/systemctl","default","--init"]
```

**Python versions in the container**
```shell
$ python --version
Python 2.7.17

$ python3 --version
Python 3.6.9
```

**Comment by gdraheim** [comment]
Supervisord is a system that should not be started in a container - it overlaps in functionality with the systemctl.py init service.

How did it get into your image anyway? From your docker file I would assume that you want to start an openssh-server which is a different thing. Please have a look at the examples in https://github.com/gdraheim/docker-systemctl-images

**Comment by jfoliveira** [comment]
Actually I was attempting to test an ansible playbook that install/restart `supervisord` service, and testing it against a docker container initialized with your systemctl replacement.
The setup works fine, but the service doesn't get started.

Might not be a suitable approach for this kind of testing.

I will have a look at the examples. Any suggestions are appreciated.
Thanks for replying Guido!

**Comment by gdraheim** [comment]
Actuatlly, supervisord is supposed to go into the CMD and running as pid 1. I do quite expect that it does exit early when that is not the case. I don't know where the logs of supervisord are - the default logs into /var/log/journal

If supervisord does not provide the necessary systemctl binary for your ansible script then the supervisord usage should be exchanged with systemctl.py completely.

**Comment by jfoliveira** [comment]
Thanks mate! I'll look at other approaches to test a playbook installing supervisord, but it's clearly not an issue with systemctl replacement. Cheers!
