### ISSUE TITLE
Service is not known to chkconfig Error when service resource executes from Chef

### ISSUE THREAD

**Issue by lhenry7** [gdraheim/docker-systemctl-replacement#111]
Using the replacement script, systemctl enable and systemctl start works for postfix, rsyslog, httpd, etc. But when I run my chef script(in standalone mode, not chef server), the service resource throws "Service is not known to chkconfig" Error, as below examples. Even chkconfig works from the command line, as it calls systemctl anyway.  Any ideas on why this wouldn't work from chef?
 
 * service[ntpd] action enable[2020-12-09T09:26:06-05:00] INFO: Processing service[ntpd] action enable (ntp::default line 112)

    * service[ntpd]: Service is not known to chkconfig.
    ================================================================================
    Error executing action `enable` on resource 'service[ntpd]'
    ================================================================================

    Chef::Exceptions::Service
    -------------------------
    service[ntpd]: Service is not known to chkconfig.

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/ntp/recipes/default.rb

    112: service node['ntp']['service'] do
    113:   supports :status => true, :restart => true
    114:   action   [:enable, :start]
    115: end

  * service[rsyslog] action enable[2020-12-09T09:25:06-05:00] INFO: Processing service[rsyslog] action enable (system-setup::default line 51)

    * service[rsyslog]: Service is not known to chkconfig.
    ================================================================================
    Error executing action `enable` on resource 'service[rsyslog]'
    ================================================================================

    Chef::Exceptions::Service
    -------------------------
    service[rsyslog]: Service is not known to chkconfig.

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/system-setup/recipes/default.rb

     51: service 'rsyslog' do
     52:   supports :restart => true, :reload => true
     53:   action :enable
     54: end
     55:

  * service[apache2] action enable[2020-12-09T09:22:17-05:00] INFO: Processing service[apache2] action enable (apache2::default line 267)

    * service[apache2]: Service is not known to chkconfig.
    ================================================================================
    Error executing action `enable` on resource 'service[apache2]'
    ================================================================================

    Chef::Exceptions::Service
    -------------------------
    service[apache2]: Service is not known to chkconfig.

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/apache2/recipes/default.rb

    267: service 'apache2' do
    268:   service_name node['apache']['package']
    269:   case node['platform_family']
    270:   when 'rhel'
    271:     reload_command '/sbin/service httpd graceful'
    272:   when 'debian'
    273:     provider Chef::Provider::Service::Debian
    274:   when 'arch'
    275:     service_name 'httpd'
    276:   end

**Comment by lhenry7** [comment]
Just tried adding 'provider Chef::Provider::Service::Systemd' to the service resource, seems to work!

**Comment by gdraheim** [comment]
Well, deployment tools like ansible will always push service-enable targets to systemctl so there was no need so far to check if it works when an old-style "chkconfig" is still used.
It may be that the systemd package overrides "chkconfig" with a variant that relays the call. It does not mean that the systemd daemon is actually run. ;)
