### ISSUE TITLE
How to return process information under service.

### ISSUE THREAD

**Issue by zhangfeng0115** [gdraheim/docker-systemctl-replacement#113]
Query service status：The process under the service was not returned.
e.g.: 
`systemctl status svm.svmnginx.1.service
svm.svmnginx.1.service - svm.svmnginx.1 controller
    Loaded: loaded (/usr/lib/systemd/system/svm.svmnginx.1.service, disabled)
    Active: active (running)
`

**Comment by gdraheim** [comment]
I had started to work on that about a week ago. Please have a look at the /develop branch.

You're welcome to provide comments and patches as I am not quite sure how the process information is being actually used. The systemctl.debug.log file is far more interesing when analyzing problems - the process information on the status screen will not help much from my perspective.

**Comment by zhangfeng0115** [comment]
Thank you for the reply.
I have a program that uses systemctl status svm.svmnginx.1.service to get the process pid, process name, and process startup parameters. The program periodically obtains the status of the program to determine its survival.
Note: the environment is Python 2.7.5.

[Let me first refer to the content of this link.](https://github.com/gdraheim/docker-systemctl-replacement/commit/55194f12f3a32c88e0722a2563d623f39b540f9a)

You have already started to do it, and I have no other questions for the time being. Thank you.

**Comment by zhangfeng0115** [comment]
We look forward to your early coding.

**Comment by gdraheim** [comment]
Hello @zhangfeng0115 
The output of "system status" is meant to be human-readable. Please use "systemctl show" for the machine-readable format. You can use "systemctl show -p MainPID" to select a single property. Tools like ansible are using that functionality to test the target status, so it is supported by the systemctl replacement tool from early on.
