### ISSUE TITLE
Check for EnvironmentFile existence misses % expansion

### ISSUE THREAD

**Issue by airtower-luna** [gdraheim/docker-systemctl-replacement#115]
I noticed template units with `EnvironmentFile=/etc/my-service/%i.conf` failing with log messages like this:
```
ERROR:systemctl: my-service@instance0.service: Failed to load environment files: /etc/my-service/%i.conf
```

The problem is that the following code does not expand the `%i` before checking if the file exists:
https://github.com/gdraheim/docker-systemctl-replacement/blob/4ceae78b24207cd86473db722a01e2f99e698d23/files/docker/systemctl3.py#L5102-L5106

Applying `expand_special()` as follows in line 5104 fixes the problem for me.
```py
            if not os.path.isfile(os_path(self._root, self.expand_special(env_file, conf))):
```

**Comment by gdraheim** [comment]
You're right, it gets expanded in all the other places. :)

**Comment by airtower-luna** [comment]
Thank you! :slightly_smiling_face:
