### ISSUE TITLE
Empty log output when less isn't available

### ISSUE THREAD

**Issue by nantiferov** [gdraheim/docker-systemctl-replacement#117]
Hi,

Thanks for a great systemd alternative. I use it for testing purposes, really useful.
Just found small issue with log handling. 

When you try to check logs for unit with `systemctl log unit_name` and there is no `less` installed, it just show nothing, like there are no logs. It took me some time to find `-vvv` option and find the root cause.

So probably it's possible to add check for this?

My environment: `ubuntu:18:04` running in Docker.
Log:
```
# systemctl log mysql -vvvv
INFO:systemctl:EXEC BEGIN /usr/bin/systemctl log mysql --system
DEBUG:systemctl:======= systemctl.py log mysql
DEBUG:systemctl:found 9 sysd files
DEBUG:systemctl:found 3 sysv files
DEBUG:systemctl:journalctl zookeeper.service -> ['/usr/bin/less', '/var/log/journal/mysql.service.log']
```

**Comment by gdraheim** [comment]
Actually, the original systemd scripts use less as well, so I wonder how they do work with such a minimal system.

Over the last years I have seen that the docker images for base operating systems have been slimmed down more and more. While the docker images were originally quite like a base system on a virtual machine they come now with barely more than a libc. I would recommend to work around that trend by installing base binaries that you want to use for debugging into your custom images.

One could surely check for the binary to avoid an error message itself but then you would still see no output. Please have a look for "SYSTEMD_LESS" that systemd was originally depending on "less".

**Comment by nantiferov** [comment]
Ok, let's hope this issue will help others who will have the same issue and waste time on debugging.
