### ISSUE TITLE
Journalctl wrapper fails if systemctl replacement named differently from `systemctl3.py`

### ISSUE THREAD

**Issue by nantiferov** [gdraheim/docker-systemctl-replacement#118]
Hi,

And also found small issue with journalctl wrapper. It has predefined name for systemctl wrapper https://github.com/gdraheim/docker-systemctl-replacement/blob/master/files/docker/journalctl3.py#L18

However, AFAIK, if I want to use `systemctl3.py` as a replacement for systemd, I will name it `systemctl`. 
And in this case journalctl will fail like this
```
# journalctl -u mysql
Traceback (most recent call last):
  File "/usr/bin/journalctl", line 32, in <module>
    os.execvp(cmd[0], cmd)
  File "/usr/lib/python3.6/os.py", line 559, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.6/os.py", line 583, in _execvpe
    exec_func(file, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```
This is cmdline `['/usr/bin/systemctl3.py', 'log', 'mysql']`

It could be fixed by keeping `systemctl3.py` as is with symlink to `systemctl`, but it looks overcomplicated for me.

**Comment by gdraheim** [comment]
The journalctl script came from a patch - see issue #99 

I guess one would need to patch journalctl.py while installing it to /usr/bin

**Comment by nantiferov** [comment]
It is, but I think that if the goal is to make replacement for systemd, it would be better to use systemctl by default.
