### ISSUE TITLE
incorrect return value on start when service is already started

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#12]
# systemctl start rsyslog
    ERROR:systemctl:the service is already running on PID 109

Command exits with return value `1` which is wrong (this is not an error condition).
Note that _systemd_ returns `0` in such case (same as _SysV_).

**Comment by gdraheim** [comment]
this should be fixed now

**Comment by onlyjob** [comment]
Thanks. :)
