### ISSUE TITLE
Plus sign in ExecStartPre value not handled

### ISSUE THREAD

**Issue by kevinburkemeter** [gdraheim/docker-systemctl-replacement#126]
A recent version of systemd allowed you to start commands with a plus sign, to indicate full privileges:

> If the executable path is prefixed with "+" then the process is executed with full privileges. In this mode privilege restrictions configured with User=, Group=, CapabilityBoundingSet= or the various file system namespacing options (such as PrivateDevices=, PrivateTmp=) are not applied to the invoked command line (but still affect any other ExecStart=, ExecStop=, … lines).

However the systemctl replacement here tries to look for commands with a `+` sign prefixed, as indicated by this error message.

```
ERROR:systemctl: default-route-check.service: Exec is not an absolute path:  ExecStartPre=+/bin/bash somecommand
ERROR:systemctl: default-route-check.service: Exec command does not exist: (ExecStartPre) +/bin/bash
ERROR:systemctl: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR:systemctl: The SystemD ExecXY commands must always be absolute paths by definition.
ERROR:systemctl: Oops, 1 executable paths were not found in the current environment. Refusing.
ERROR:systemctl: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by gdraheim** [comment]
The message is correct as the "+" feature is not implemented. May be you could join #97  in the effort to get to an implementation.
