### ISSUE TITLE
ERROR:systemctl:unsupported run type 'dbus'

### ISSUE THREAD

**Issue by coldspark29** [gdraheim/docker-systemctl-replacement#129]
First of all, I am not sure if I have set this up right. I have installed ``python`` and ``systemd`` in the container, which is automatically installed by packages using it. Then I have removed the binary and created a symlink to the ``systemctl.py``, that I have previously copied in ``/usr/bin``

```
rm /usr/bin/systemctl
ln -s /usr/bin/sytemctl.py /usr/bin/systemctl
```

I am now trying to run a script which heavily relies on systemd and docker and it has returned

``ERROR:systemctl:unsupported run type 'dbus'``

I already tried starting dbus according to https://georgik.rocks/how-to-start-d-bus-in-docker-container/, 
but the error persists.

**Comment by gdraheim** [comment]
The systemctl script does not recreate systemd. Actually it tries hard to avoid systemd services that are tightly connected to a systemd daemon. The .service files can be of a different "Type=" and so far I did not come across a "Type=dbus" - what kind of service is that?

**Comment by coldspark29** [comment]
It was the network-manager. I was trying to run Home Assistant in a container, which uses docker containers and systemd to control parts of the system. It was not a good idea and I found another solution without doing everything in docker.
