### ISSUE TITLE
`systemctl stop` leaves .PID file behind when daemon is not running

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#13]
When daemon is not running (e.g. terminated, crashed, etc.) `systemctl stop` prints the following error:

    kill: cannot find process ""

(My .service file contains `ExecStop=/bin/kill ${MAINPID}`).

The problem is that even though process is not there, `systemctl` does not remove PID file from `/run` on _stop_.

**Comment by gdraheim** [comment]
I have been working out a new testsuite scenario that goes through start/stop/is-active scenarios. See "make test_4032". While working on it, I have also added a couple of remove-pid-file parts. May be your problem is fixed in current v0.8.1401

**Comment by gdraheim** [comment]
that one's done?

**Comment by gdraheim** [comment]
systemctl-stop will cleanup the pid-file, but systemctl-kill will not as shown in the testcase.
