### ISSUE TITLE
using systemctl for starting/restarting host level systemd services from inside a container

### ISSUE THREAD

**Issue by prakashmirji** [gdraheim/docker-systemctl-replacement#130]
Hello,

We have a use case where we are trying to launch a container ( we call it shephard container) from the pod to configure/manage the hosts with day 2 operations like upgrading systemd services running on the host. The pod container is configured with privileged mode and mounted with the host root / filesystem inside the pod container. It has root access to install packages using yum. Most commands are working fine except when shephard container tries to restart the systemd service using systemctl command. This command fails as the container init process is not /sbin/init.

I wanted to check - can we use your solution/scripts to our use case. Note that, we want actual work to happen on the host not on the docker container itself. I was looking at your sample test docker file, where you are running systemctl command. I think these commands are executed on the docker container right?. How do we use  your solution to run systemctl inside a container so that it works/executes with host systemd services directly.

I know this is not a typical github issue - but thought to use this for asking the question. Appreciate your response on this.

**Comment by gdraheim** [comment]
The container init process would be systemd (not /sbin/init) - here is the example from my pc:

      1 ?        Ss     0:09 /usr/lib/systemd/systemd --switched-root --system --deserialize 29

There is an older trick to mount a number of /sys directories into the container so that the container's systemd commands will talk to the systemd of the host. Look for Dan Walsh from Redhat talking about how to run systemd within a docker container. I did never use that as it was my intention to have a docker container run without extra priviledges (or special mappings).

If you want to pick up my script then you may want to check whether it can use the systemd configuration on the host by using the "-root /your/host/mount/path" option. It does even modify some paths from the service descriptor files but I am not sure that it will be enough to make your approach work.

**Comment by prakashmirji** [comment]
thanks for the response.

>>  1 ?        Ss     0:09 /usr/lib/systemd/systemd --switched-root --system --deserialize 29

Do you mean the entrypoint should be `/usr/lib/systemd/systemd`

Can you please share the command that I can use on the entrypoint?

I tried Dan Walsh approach to build the container image using the dockerfile that Dan has put up [1]. When I tried that with centos:7 image, I still get dbus error.

my command looks like this

```
docker run -it --rm  --cap-add SYS_ADMIN --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro prakashmirji/ezlcm_systemd-v2:v1 systemctl status kubelet
```

I get below error 

```
Failed to get D-Bus connection: Operation not permitted
```

Here is the dockerfile I used

```
FROM centos:7
ENV container docker
RUN yum -y update; yum clean all
RUN yum -y install systemd; yum clean all; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*; \
rm -f /etc/systemd/system/*.wants/*; \
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*; \
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
```

Any pointers to troubleshoot would be helpful

[1]https://developers.redhat.com/blog/2014/05/05/running-systemd-within-docker-container

**Comment by gdraheim** [comment]
I can not help with the details, I am sorry.

I just wonder why cmd-args are sent to the docker-run as it would need to be handled by the cmd/entrypoint. I guess that it skips the systemd start so that it can not work.
