### ISSUE TITLE
ExecStartPre seems broken when cmd has args

### ISSUE THREAD

**Issue by mvorisek** [gdraheim/docker-systemctl-replacement#131]
`mysql-server` package installed using apt from mysql.com on Debian 11 has the following config:

```
[Unit]
Description=MySQL Community Server
Documentation=man:mysqld(8)
Documentation=http://dev.mysql.com/doc/refman/en/using-systemd.html
After=network.target
[Install]
WantedBy=multi-user.target
[Service]
User=mysql
Group=mysql
Type=notify
PermissionsStartOnly=true
ExecStartPre=/usr/share/mysql-8.0/mysql-systemd-start pre
ExecStart=/usr/sbin/mysqld
TimeoutSec=0
LimitNOFILE = 10000
Restart=on-failure
RestartPreventExitStatus=1
```

but when started with `docker-systemctl-replacement` (using `systemctl start mysql`), the following is printed:

```
ERROR:systemctl:the ExecStartPre control process exited with error code
```

and the exit code is non-zero. But when started directly using `/usr/share/mysql-8.0/mysql-systemd-start pre`, it executes well with zero exit code.

It seems `docker-systemctl-replacement` can not handle the argument or something else is wrong.

**Comment by gdraheim** [comment]
The Pre-code can surely handle arguments just fine. However PermissionsStartOnly is an undocumented feature of systemd which seems to make the Pre-call to run as root instead of using the specified User/Group.

Please inform the upstream developer to check the service descriptor.

**Comment by mvorisek** [comment]
@gdraheim thanks for a quick reply!

@dahlerlend can you please look at it from MySQL side /wo using `PermissionsStartOnly`?
