### ISSUE TITLE
How to install it on centos7 container?

### ISSUE THREAD

**Issue by amarjit-singh** [gdraheim/docker-systemctl-replacement#147]
I never installed anything from the source. I followed some tutorials to install a package from the source but they refer to a file named "configure" in the root directory of the repo. But this repo doesn't have this file.

    Moreover, when I executed the following command `make install`, I get the following error.

> make: *** No rule to make target `install'.  Stop.

**Comment by gdraheim** [comment]
This project does not need a build step. I don't what know which source you are referring to.
