### ISSUE TITLE
Uable to start postgresql service

### ISSUE THREAD

**Issue by maxatlas** [gdraheim/docker-systemctl-replacement#150]
sh-4.2# systemctl start -vvv postgresql
INFO:systemctl:EXEC BEGIN /usr/bin/systemctl start postgresql --system
DEBUG:systemctl:======= systemctl.py start postgresql
DEBUG:systemctl:found 200 sysd files
DEBUG:systemctl:found 6 sysv files
INFO:systemctl:system is offline
DEBUG:systemctl:'/usr/lib/systemd/system/postgresql.service' no --user mode >> accept
DEBUG:systemctl: start unit postgresql.service => '/usr/lib/systemd/system/postgresql.service'
DEBUG:systemctl:extra-vars []
INFO:systemctl: pre-start '/usr/bin/postgresql-check-db-dir' '/var/lib/pgsql/data'
DEBUG:systemctl: pre-start done (OK) <->
INFO:systemctl:forking start '/usr/bin/pg_ctl' 'start' '-D' '/var/lib/pgsql/data' '-s' '-o' '-p 5432' '-w' '-t' '300'
INFO:systemctl:forking started PID 243
INFO:systemctl:forking stopped PID 243 (1) <->
WARNING:systemctl:No PIDFile for forking '/usr/lib/systemd/system/postgresql.service'
DEBUG:systemctl:writing to /run/postgresql.service.status
        ActiveState=failed
DEBUG:systemctl:writing to /run/postgresql.service.status
        ExecMainCode=1
WARNING:systemctl:forking start not active

**Comment by gdraheim** [comment]
The problem seems to be in the logs of postgres. There are older examples for postgres in https://github.com/gdraheim/docker-systemctl-images
