### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by vmalenev** [gdraheim/docker-systemctl-replacement#152]
Hello.
I need systemctl in docker for rocky linux 9, but in rhel9 python2 have EOL state and not supported.
Do you plan migrating to python3?

**Comment by gdraheim** [comment]
Are you kidding me?

**Comment by gdraheim** [comment]
systemctl3.py had been available all the time, and only the shebang was different.

When I published the package onto pypi.org, I made the python3 to be the one for /usr/bin/systemctl.py
