### ISSUE TITLE
systemctl disable not disabling service at container restart

### ISSUE THREAD

**Issue by JCoupalK** [gdraheim/docker-systemctl-replacement#164]
Inside my docker container running Ubuntu 22.04 when I do: 
```
sudo systemctl disable nginx
sudo systemctl stop nginx
```
And then outside of it do a `docker restart` or `docker stop` and then `start`

My service comes back up.

But when I do `sudo systemctl status nginx` after a restart I get this which I found strange:
```
nginx.service - A high performance web server and a reverse proxy server
    Loaded: loaded (/usr/lib/systemd/system/nginx.service, disabled)
    Active: active (running)
```
The service is disabled but it somehow comes back up.

My dockerfile has `CMD ["/usr/bin/systemctl"]`

I'm new to this project so I'm not sure if that's normal behavior or not.

**Comment by gdraheim** [comment]
The system startup is actually doing a "systemctl start default.target" which is a symlink doing "systemctl start multi-user.target". In the nginx.service you find a declaration that it is a dependency of the multi-user.target.

The systemctl designers have a funcationality for you however - it is called "systemctl mask nginx".
