### ISSUE TITLE
/usr/sbin/runuser vs /sbin/runuser

### ISSUE THREAD

**Issue by lifeofguenter** [gdraheim/docker-systemctl-replacement#22]
in ubuntu the path of `runuser` is `/sbin/runuser` not sure if there is a better way of handling that other than a hardcoded path

**Comment by gdraheim** [comment]
well, one can test for the existance of `/sbin/runuser` ... done that now.

**Comment by gdraheim** [comment]
Did the commit with the wrong issue-id but its actually there. Please have a test. Thanks in advance.

**Comment by gdraheim** [comment]
Probably ok.
