### ISSUE TITLE
please clarify license; please improve license grant(s).

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#3]
It would be great if you could clarify license and improve license grant as well.

It is best to refer to the chosen license by its standard [SPDX name](https://spdx.org/licenses/) as well as to include URL of the full canonical text of the license (as below).

You have to provide full text of the license with your software as well.

Also it would be best to add `LICENSE` file to the repository root to make it clear that license applies not only to main executable but also to tests, documentation files, etc.

Current statement inside `systemctl.py` is ambiguous:

> (CC-BY, GPL, BSD)

"CC-BY" is ambiguous. See [how to apply CC license](https://creativecommons.org/faq/#how-do-i-apply-a-creative-commons-license-to-my-material) instructions. Basically you have to use standard attribution text (so license can be detected automatically, etc) and include link to full text of the license. Please note that Creative Commons (recommends to) use a versioned license and it is always best to use the latest version.

---

"GPL" is ambiguous. Please follow [instructions](https://www.gnu.org/licenses/gpl-howto.html). You have to include full text of the license grant:

~~~~
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
~~~~

---

"BSD" is [extremely ambiguous](https://fedoraproject.org/wiki/Licensing:BSD) and perhaps it is not the best license anyway. You probably want to use either [BSD-2-Clause](https://opensource.org/licenses/BSD-2-Clause) or [MIT](https://opensource.org/licenses/MIT) a.k.a. [Expat](https://www.gnu.org/licenses/license-list.html#Expat) license (or even [Apache-2.0](https://opensource.org/licenses/Apache-2.0) license).

---

Thank you.

**Comment by gdraheim** [comment]
It's been itentionally relaxed in its wording but I'll check that again when heading more towards the 1.0 release.

**Comment by gdraheim** [comment]
I have just learned about the EU Public License which allows relicensing to whatever is wanted. Plus they have some serious legal department to defend the rules. And clarify them if needed.

**Comment by gdraheim** [comment]
A license file has been included in the software repository and the copyright notice has been changed to "licensed under the EUPL" to have the work protected by a powerful body.
