### ISSUE TITLE
restart fails even though service is running

### ISSUE THREAD

**Issue by lifeofguenter** [gdraheim/docker-systemctl-replacement#31]
```
# cat /run/nginx.service.status
ActiveState=failed
ExecStopCode=1
```

```
# ps -e | grep $(cat /run/nginx.pid)
24740 ?        00:00:00 nginx
```

```
# netstat -lnp | grep $(cat /run/nginx.pid)
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      24740/nginx: master
```

```
# cat /lib/systemd/system/nginx.service
[Unit]
Description=The NGINX HTTP and reverse proxy server
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t
ExecStart=/usr/sbin/nginx
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s QUIT $MAINPID
PrivateTmp=true
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by lifeofguenter** [comment]
seems to be a regression, downgrading to https://github.com/gdraheim/docker-systemctl-replacement/blob/v1.2.2177/files/docker/systemctl.py makes it work again.

**Comment by gdraheim** [comment]
I can not reproduce the problem. I have created test_8081 that does install nginx, does start on it, and the a restart. All of it works fine.

Can you expand on the problematic environment?

**Comment by gdraheim** [comment]
Do you have some time to show me how to reproduce it?

**Comment by lifeofguenter** [comment]
Sorry, will try to find some time to make it proper reproducible. Right now I am having similar issue with the official powerdns-4.1 deb packages.

Both cases are on Debian 9 - not centos - maybe that is where the issue is?

**Comment by gdraheim** [comment]
I do still have no update on how to reproduce it.

**Comment by gdraheim** [comment]
I had never been able to reproduce this.
