### ISSUE TITLE
Overlapping "notify" socket name: (Device or resource busy: '/var/run/systemd/notify')

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#35]
In [rkt](https://github.com/rkt/rkt) container runtime `/var/run/systemd/notify` socket inside containers is used to proxy notifications to the host.

Unfortunately _systemctl_ replacement tries to use path to notify socket that is identical to the one owned/controlled by host's systemd.

Naturally there is an error when _systemctl_ replacement attempts to use someone else's notify socket which it did not create:

~~~~
# systemctl start php7.2-fpm.service
Traceback (most recent call last):
  File "/usr/local/bin/systemctl", line 3913, in <module>
    result = command_func(*modules)
  File "/usr/local/bin/systemctl", line 1538, in start_modules
    return self.start_units(units, init) and found_all
  File "/usr/local/bin/systemctl", line 1545, in start_units
    if not self.start_unit(unit):
  File "/usr/local/bin/systemctl", line 1564, in start_unit
    return self.start_unit_from(conf)
  File "/usr/local/bin/systemctl", line 1680, in start_unit_from
    notify = self.notify_socket_from(conf)
  File "/usr/local/bin/systemctl", line 1464, in notify_socket_from
    os.unlink(socketfile)
OSError: [Errno 16] Device or resource busy: '/var/run/systemd/notify'
~~~~

Renaming `_notify_socket_name` to avoid clash fixes the problem.

**Comment by gdraheim** [comment]
Well, I had heard that rkt has a working systemd - which leads to the question why to use systemctl.py in that environment?

Other than that I am simply insecure about the behaviour. Do all applications honour the environment variable for notify_socket? Or do they assume that it is /var/run/systemd/notify ? As it is a kind of standard path I had opted to do the same: do it like systemd does it.

**Comment by onlyjob** [comment]
Even if I could use systemd in my _rkt_ container as init system, there might be reasons to prefer systemctl replacement. That's beyond the point.
_rkt_ have good integration with systemd but systemd is notoriously difficult to use as init system in unprivileged containers.

In _rkt_ containers this socket is already taken. You shouldn't have tried to use well known socket path so collision could have been avoided.

My change merely allows to resolve collision by using somewhat unique socket file name for systemctl replacement... Most apps do the same - use their own socket file.
It is a pragmatic change that breaks nothing yet fixes the problem in non-Docker container runtime. What else do you expect to be convinced?

**Comment by gdraheim** [comment]
Well, if there are enough implementations that expect to use a default path then everything else is a bad idea.

Anyway, I did some research about the current state of client-side implementations and it is actually looking good.

https://www.freedesktop.org/software/systemd/man/sd_notify.html => "If the unset_environment parameter is non-zero, sd_notify() will unset the $NOTIFY_SOCKET environment variable before returning (regardless of whether the function call itself succeeded or not). Further calls to sd_notify() will then fail, but the variable is no longer inherited by child processes."

https://github.com/opencontainers/runc/blob/master/notify_socket.go => newNotifySocket() .... filepath.Join(root, "notify.sock")

And a hint on systemd 901 that type=notify processes have problems when $NOTIFY_SOCKET was not set.

.... so it the state of the art that no fallback shall be assumed for $NOTIFY_SOCKET, and any client-side calls should fail if the variable is missing.

**Comment by gdraheim** [comment]
I would like to implement this a bit different however. Looking at the code, any old notify-socket gets unlinked before being opened as a notify-socket for the service that we would like to start next. Obviously there may be an overlap when starting multiple services as from init, and there is a potential scenario where two systemctl.py process run in parallel trying to unlink/create the same socket file.

Instead I would propose to create a notify-socket per service that systemctl.py wants to interact with. That's going to be very similar to the lock file that is created per service now. Evey message sent over that socket may in fact get to any systemctl.py that is active at the time. Shouldn't be a problem, right? And it is not  a problem to have a number of old notify-socket files around - it is liimited to the number of services that we have.

**Comment by gdraheim** [comment]
You're patch is correct, I did just want to go a bit beyond that. ;) 

.... so now it's NOTIFY_SOCKET=/var/run/systemd/notify.httpd.service

**Comment by onlyjob** [comment]
This is perfect - per service sockets. :) I like that.

Thanks.
