### ISSUE TITLE
Please implement "is-system-running" command as proxy

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#37]
Detecting whether systemd is the active init system may be difficult if _systemctl_ replacement is in the PATH.

What would be helpful is to implement `systemctl is-system-running` as proxy to the original systemctl command so when `is-system-running` is given we find original `systemctl` executable and call it.

**Comment by gdraheim** [comment]
That's about a hidden feature for me, I did never hear of that.

I do get "degraded" on my Linux desktop and exitcode = 1

When looking at the table then I would actually assume that systemctl.py should return running/degraded itself when it is active as an init-replacement.

https://www.freedesktop.org/software/systemd/man/systemctl.html#is-system-running

.... but I gues you meant that it should report "unknown" ?

**Comment by gdraheim** [comment]
f4e2cf54ae89374462d52061386d60e5883da916

an implementation is provided but testcases are still missing.
