### ISSUE TITLE
No output for systemctl start SERVICE

### ISSUE THREAD

**Issue by cfdraper** [gdraheim/docker-systemctl-replacement#38]
Beginning in version 1.3.2236, `systemctl start SERVICE` no longer prints the output of the service as it starts. If this is deliberate, is there a way to enable the output?

**Comment by gdraheim** [comment]
At the moment I can not see to implement a global log-to-console get implemented for the upcoming version 1.4.

As for the question: if you do rely on the console-output then you may need to stay on an earlier release (e.g. 1.2). I am trying to allow systemctl.py to cover more scenarios of running a systemd-related service but if your service runs fine with an older version of systemctl.py then it is a good thing to do.
