### ISSUE TITLE
repeated calls to unmask don't work

### ISSUE THREAD

**Issue by Crack** [gdraheim/docker-systemctl-replacement#46]
It should be possible to unmask an already unmasked unit:
```
root@653efcc50970:/etc/puppet# systemctl mask influxdb
root@653efcc50970:/etc/puppet# systemctl unmask influxdb
root@653efcc50970:/etc/puppet# systemctl unmask influxdb
ERROR:systemctl:target is not a symlink: /etc/systemd/system/influxdb.service
```
Last call should succeed.

**Comment by gdraheim** [comment]
> sudo systemctl mask mariadb
    Created symlink /etc/systemd/system/mariadb.service → /dev/null.
    > echo $?
    0
    > sudo systemctl mask mariadb
    > echo $?
    0
    > sudo systemctl unmask mariadb
    Removed /etc/systemd/system/mariadb.service.
    > echo $?
    0

**Comment by gdraheim** [comment]
v1.4.2416 ... I have modified the implementation to check that it was already removed.

Not backed by testcase so far.

**Comment by Crack** [comment]
Thanks! It works now.

**Comment by gdraheim** [comment]
Already in release v1.4.2456
