### ISSUE TITLE
Does not fail when `EnvironmentFile` does not exist.

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#5]
Service with `EnvironmentFile=/path/do-not-exist` starts anyway and does not fail to start (when it should).
Note that `EnvironmentFile=-/path/do-not-exist` should allow service start when file is not found.

**Comment by gdraheim** [comment]
Actually it should bump into a file-not-found exception.

    def read_env_file(self, env_file): # -> generate[ (name,value) ]
        """ EnvironmentFile=<name> is being scanned """
        if env_file.startswith("-"):
            env_file = env_file[1:]
            if not os.path.isfile(env_file):
                return
        try:
            for real_line in open(env_file): # <<<<<<<<<<<<<<<<<

Can you give an example where it does fail quickly?

**Comment by gdraheim** [comment]
fixed along with test_3060
