### ISSUE TITLE
Make unmask not fail for services in /etc/systemd/system/

### ISSUE THREAD

**Issue by Crack** [gdraheim/docker-systemctl-replacement#50]
unmask fails when I use it with services placed directly into /etc/systemd/system/, eg.
```
root@bd1:/etc/puppet# systemctl unmask kafka
ERROR:systemctl:target is not a symlink: /etc/systemd/system/kafka.service
```
In my case it fails with Puppet service resource, because when starting a service it unconditionally unmasks it.

It should do nothing and return successfully, like real systemd:
```
$ systemctl --version
systemd 229
$ ls -la /etc/systemd/system/kibana.service
-rw-r--r-- 1 root root 466 Jun 30 00:08 /etc/systemd/system/kibana.service
$ sudo systemctl unmask kibana
$ echo $?
0
```

**Comment by gdraheim** [comment]
May be it helps to just reduce the error to a warning message.

In any case, deployment tools should be idempotent so that an action is only performed when needed. From my point of view this is a Puppet bug that works due to some helpful (not quite specified) behaviour of systemd's systemctl. ;)

**Comment by gdraheim** [comment]
Already in release v1.4.2456
