### ISSUE TITLE
Support for .include directive

### ISSUE THREAD

**Issue by avidspartan1** [gdraheim/docker-systemctl-replacement#54]
It looks like the '.include' directive is not supported by the systemctl script. For example, I'm running into an issue where "/etc/systemd/system/postgresql-9.6.service" has a line at the top that looks like this:

```
.include /usr/lib/systemd/system/postgresql-10.service
```

When I try to use systemctl.py to start the service, it reports:

```
ERROR:systemctl:Unit postgresql-9.6.service could not be found.
```

I know that the service file is valid because this command:

```
systemd-analyze verify postgresql-9.6.service
```

Gives me an exit code of 0.

**Comment by gdraheim** [comment]
What's missing here is a testcase however.

**Comment by gdraheim** [comment]
I have tried to find a definition of the include-syntax but the sytemd documentation is silent about that.

https://www.freedesktop.org/software/systemd/man/systemd.syntax.html

**Comment by avidspartan1** [comment]
The only indication I've found that '.include' is official is:

1. systemd-analyze verify <service-name> does not report any issues
2. This article: https://www.certdepot.net/rhel-7-systemd-unit-file-customization/

I ran across this issue when trying to use the postgresql Puppet module from Puppetlabs. In their template for /etc/systemd/system/postgresql-<version>.service, they use the '.include' directive. It seems to be a "hidden" feature?

**Comment by gdraheim** [comment]
Yes, we will keep this feature. A recursive call is actually a simple solution that is "safe and sound".

I will open a bug ticket on systemd to notify them. They should actually mention the old feature in their documentation somewhere as officially "deprecated". I guess they did simply forget about it - as "systemd-analyze" does not mark any problems about it.

**Comment by gdraheim** [comment]
Systemd is about to mark it officially as "deprecated".

https://github.com/keszybz/systemd/commit/37d5c1087a01feeb901f16446c1437c26ccb4831

However systemd will continue to support the syntax - with a warning.
Possibly systemctl.py should also print a warning message when coming across that feature.

**Comment by gdraheim** [comment]
I have done so, adding an error-message but not breaking the parsing step itself.

As this feature is  deprecated I do not care for a testcase. That allows to close the issue.

Thanks for your help, I do really appreciate that.

**Comment by avidspartan1** [comment]
You're very welcome--thanks for authoring this awesome tool!
