### ISSUE TITLE
Use unit file to start service automatically

### ISSUE THREAD

**Issue by gowenpotato** [gdraheim/docker-systemctl-replacement#60]
Hello there,

Not a bug but as I'm not familiar with unit files (though I have tried to figure the answer out) I can't quite work out how to start a service automatically when I pass /usr/bin/systemctl as the entrypoint.

I've tried combining with CMD (just appends to /usr/bin/systemctl so not useful)
I also tried creating a symlink to the service (/lib/systemd/system/strongswan-swanctl.service) to no avail
I also replaced "Requires=basic.target" with "Requires=basic.target strongswan-swanctl.service" in the "/lib/systemd/system/graphical.target" file

each time from the systemctl output the module is failed

Could you give me a pointer on how to get this working?

Thanks

**Comment by gdraheim** [comment]
Just `"systemctl enable xy.service"` and it will be in the `"systemctl default-services"`. The latter are started when systemctl is the CMD without any further arguments.

You could also use `"systemctl --init start xy.service"` in the CMD or shorter `"systemctl init xy.service"`. 

The "default" target is not "graphical.target" but "multi-user.target". So that may have a share in the problem space as well. Most laptops run on graphical.target and most www servers run on multi-user.target. Changing the default with "set-default" is possible but not recommended.

**Comment by gowenpotato** [comment]
If I just leave the dockerfile with entrypoint set to systemctl only I can see my service when I run `"systemctl default-services"` and the service is 

```
C:\WINDOWS\system32>docker exec 399c258cd496   systemctl status strongswan-swanctl.service
strongswan-swanctl.service - strongSwan IPsec IKEv1/IKEv2 daemon using swanctl
    Loaded: loaded (/lib/systemd/system/strongswan-swanctl.service, enabled)
    Active: failed (failed)
```

I can enable the service with `docker exec --privileged 399c258cd496   systemctl start strongswan-swanctl.service`

The privileged option is required or no effect, and then I get:

```
C:\WINDOWS\system32>docker exec 399c258cd496   systemctl status strongswan-swanctl.service
strongswan-swanctl.service - strongSwan IPsec IKEv1/IKEv2 daemon using swanctl
    Loaded: loaded (/lib/systemd/system/strongswan-swanctl.service, enabled)
    Active: active (running)
```

combining an entrypoint with a CMD is problematic for me - I have tried the permutations of https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact but still didn't work

Could it just be an awkward app?

**Comment by gdraheim** [comment]
Well, Strongswan is a networking tool, so I do not know if it can work with the virtual bridge created by docker. So perhaps a priviledged mode is needed. There should be some logs about the failing status. If the service does not create a log file on it sown then systemctl may have some in /var/log/xy.service.log

If a dockerized service does not consume arguments then just go for CMD. Both will come out fine as PID 1. But a docker image with a CMD is easier to debug as you do no tneed to know about -entrypoint=xx.

**Comment by gowenpotato** [comment]
Yes that makes sense, thanks very much for your help, and thanks for writing/sharing this code!

**Comment by gowenpotato** [comment]
Not sure if this will be of any help to anyone who chances accross it, but the fix was to to use the run command with the --privileged flag, then strongswan-swanctl came up in an automatic fashion
