### ISSUE TITLE
"oldest" COVERAGE option does not work

### ISSUE THREAD

**Issue by bvegso** [gdraheim/docker-systemctl-replacement#61]
the documentation does not really talk about the use-case for COVERAGE and the "oldest" option but what i realised when trying to use this systemctl replacement in a chroot environment into a CentOS 7 system, sometimes after a successful service start operation, the status file would be truncated by the truncate_old sub. get_boottime tries to determine the boottime, based on the firsts 10 pids, but if the "oldest" COVERAGE option is given, it would go and find the oldest pid in the system. unfortunately even though it finds this oldest pid, it never returns with that value, it just looks for it.

see: https://github.com/gdraheim/docker-systemctl-replacement/blob/ca7fec9e811617b1b84e0256bee3970c7ca07266/files/docker/systemctl3.py#L1339

it should read:
`return self.get_boottime_oldest()`

both v2 and v3 affected

**Comment by gdraheim** [comment]
Well, I am not sure why this option has been introduced. But I do agree with you that the intention has been to simply return the value upfront. Fixed on v1.4.3147
