### ISSUE TITLE
systemctl daemon-reload getting error

### ISSUE THREAD

**Issue by peacengell** [gdraheim/docker-systemctl-replacement#63]
Hello, install the systemctl.py on a docker ubuntu:1604 imageand getting this error after runnning systemctl daemon-reload
```
INFO:systemctl:EXEC BEGIN /bin/systemctl daemon-reload --system
DEBUG:systemctl:======= systemctl.py daemon-reload
DEBUG:systemctl:found 201 sysd files
Traceback (most recent call last):
  File "/bin/systemctl", line 4438, in <module>
    result = command_func()
  File "/bin/systemctl", line 3511, in system_daemon_reload
    for unit in self.match_units():
  File "/bin/systemctl", line 1086, in match_units
    for unit in self.match_sysd_templates(modules, suffix):
  File "/bin/systemctl", line 1043, in match_sysd_templates
    for module in modules:
TypeError: 'NoneType' object is not iterable
```

Please any help to fix this error or to debug to know what is causing this error.

Regards,

**Comment by peacengell** [comment]
Hello,

I notice that the function command_func() is returning TypeError: NoneType object.

```
>>> command_func()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not callable
>>> 
```
Debuging the script to see more insight

**Comment by peacengell** [comment]
Ok guys looks like I got a fix for now, If anyone getting the same error, please use this commit, because it's just work here.
```
commit eca23dd86c7ccf2b23296dbb0a1705e61da97a33 (HEAD)
Author: Guido Draheim <guidod@gmx.de>
Date:   Sun Apr 14 17:15:33 2019 +0200
```
I don't get those Type error on the module, looks like this features is new and seams it's complain on ubuntu:16.04 image.

I try to debug it with pdb.

**Comment by gdraheim** [comment]
Oops, I am sorry, this bug came in from a  change for #62 supporting template units.

**Comment by gdraheim** [comment]
done.
