### ISSUE TITLE
Error with Debian and SSH

### ISSUE THREAD

**Issue by mvorisek** [gdraheim/docker-systemctl-replacement#71]
With Docker image `debian:latest` a SSH server can be installed, but then when `systemctl restart ssh` is run, it fails with error code 1 without any warnings.

**Comment by gdraheim** [comment]
You can increase the log level with "systemctl restart ssh -vv" and you can also force additional logs by "touch /var/log/systemctl.debug.log" before running a command.

**Comment by mvorisek** [comment]
Here are steps to reproduce:

save:
```
apt-get update
apt-get install -y wget python procps openssh-server systemd net-tools

echo "--------------------------------------------------------------------------"
wget https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py -O /usr/bin/systemctl
chmod +x /usr/bin/systemctl
mkdir /run/systemd/
mkdir /run/systemd/system/
systemctl stop dbus.service -vv
echo "--------------------------------------------------------------------------"

ps aux
echo "--------------------------------------------------------------------------"

systemctl status ssh -vv
systemctl start ssh -vv
echo "exit code: $?"
echo "--------------------------------------------------------------------------"

netstat -l
```
under file name `run-debian-with-systemd.sh` and run:
```
cat run-debian-with-systemd.sh | docker run -i debian:latest
```

currently these two lines
```
systemctl start ssh -vv
echo "exit code: $?"
```
display the following:
```
INFO:systemctl:EXEC BEGIN /usr/bin/systemctl start ssh --system
INFO:systemctl:system is offline
INFO:systemctl: ssh.service: there should be only one ExecReload statement.
                        Use ' ; ' for multiple commands (ExecReloadPost or ExedReloadPre do not exist)
INFO:systemctl: pre-start '/usr/sbin/sshd' '-t'
INFO:systemctl:notify start '/usr/sbin/sshd' '-D'
INFO:systemctl:notify started PID 4733
INFO:systemctl:notify stopped PID 4733 (255) <->
WARNING:systemctl:notify start not active
INFO:systemctl:simple start '-/usr/sbin/sshd' '-i'
INFO:systemctl:simple started PID 4734
INFO:systemctl:simple stopped PID 4734 (1) <->
WARNING:systemctl:simple start not active
exit code: 1
```

In production we need to run the code on GitLab Runner Executor. We can set the some Docker options like volumes, but we can not set the entry point or specify `--init` Docker option. We also can not modify the Docker image before the run in any way, the GitLab Runner Executor can only copy some code to the Docker container and then in starts the container with `cat generated-bash-script | /bin/bash`.

The target use case is to test Ansible roles which uses `systemctl` to control services and we can not modify it.

Do you know what the problem is and how to make the systemctl working?

**Comment by gdraheim** [comment]
I have implemented a "make test_8071" which can reproduced the problem.

It seems that the command '/usr/sbin/sshd' '-D' fails itself, so I did try to run it in the container.

```
docker exec -it d6b2de33c8dd bash
root@d6b2de33c8dd:/# /usr/sbin/sshd -D
Missing privilege separation directory: /run/sshd
```

It may be related to these lines in /lib/systemd/system/ssh.service

```
RuntimeDirectory=sshd
RuntimeDirectoryMode=0755
```

That's not implemented.

**Comment by mvorisek** [comment]
Thanks. I have created the missing directory `` and when I run:
```
/mvorisek/systemctl.py start ssh -vv ; echo $?
```
it displays:
```
INFO:systemctl:EXEC BEGIN /mvorisek/systemctl.py start ssh --system
INFO:systemctl:system is offline
INFO:systemctl: ssh.service: there should be only one ExecReload statement.
                        Use ' ; ' for multiple commands (ExecReloadPost or ExedReloadPre do not exist)
INFO:systemctl: pre-start '/usr/sbin/sshd' '-t'
INFO:systemctl:notify start '/usr/sbin/sshd' '-D'
INFO:systemctl:notify started PID 106
INFO:systemctl:wait $NOTIFY_SOCKET, timeout 90
INFO:systemctl:notify start done 106
INFO:systemctl:simple start '-/usr/sbin/sshd' '-i'
INFO:systemctl:simple started PID 107
INFO:systemctl:simple stopped PID 107 (1) <->
WARNING:systemctl:simple start not active
1
```

the `INFO:systemctl:simple start '-/usr/sbin/sshd' '-i'` line seems wrong to me, it seems that the systemctl tries to run a command with - (dash) at the start. Do you know where does it come from?

**Comment by gdraheim** [comment]
oh oh, that's a plain bug .... there should have been a "checkstatus(cmd)" that cuts away the minus.

On the other hand, I guess that the "simple" start is related to the template-unit start where the command has been carved from

     /lib/systemd/system/ssh@.service

That's related to the problems on #69 where "ssh" should not match on "ssh@".

**Comment by gdraheim** [comment]
you can try to evade that problem by saying "start ssh.service" I guess.

**Comment by gdraheim** [comment]
.... and I have added another patch that changes the template-match behaviour.

Please test.

**Comment by mvorisek** [comment]
Thanks, the dash is fixed. Great work!

Now I can easily start the "init" `systemctl --init`.

Is there currently or can you add a possibility to set an entrypoint, i.e. command that will be executed once the init is done? I know I can start the init on background, but this will be an elegant solution to wait synchronously before all services are up. I mean something like `systemctl --init -- cmd arg1 args2...'`, this is for example what https://github.com/krallin/tini does.

**Comment by gdraheim** [comment]
Well, systemctl is a service manager, so an additional 'cmd' needs to become oneshot-type x.service. The init-loop is not about the sysvinit-level btw, that's just a side effect of starting the 'default' runlevel.

**Comment by mvorisek** [comment]
Thanks, I understand.

I found out why the directories needed to be created manually. They are created by `systemctl start systemd-tmpfiles-setup` service which is normally started at the very beginnning of the init process.

It can be be started manually and it starts and keeps runnning. The issue it that when a new service is installed (like the ssh daemon), then it needs to be restarted manually to create the files for the new service. Without it any start fails. Do you know how to make it work automatically?

**Comment by mvorisek** [comment]
This is output of the init:
```
root@07f25c56813c:/# /usr/bin/systemctl --init
cgmanager.service: cgmanager: Failed to turn /sys/fs/cgroup mount readonly: Operation not permitted
cgmanager.service: cgmanager: Failed to turn /sys/fs/cgroup mount readonly: Operation not permitted
cgmanager.service:
cgproxy.service: cgproxy: Failed to turn /sys/fs/cgroup mount readonly: Operation not permitted
cgproxy.service: cgproxy: Failed to turn /sys/fs/cgroup mount readonly: Operation not permitted
cgproxy.service:
ssh.service: Missing privilege separation directory: /run/sshd
ssh.service: Missing privilege separation directory: /run/sshd
ssh.service: Missing privilege separation directory: /run/sshd
ssh.service: Missing privilege separation directory: /run/sshd
ssh.service:
```

But if I start the SSH manually like:
```
root@07f25c56813c:/# systemctl start systemd-tmpfiles-setup
root@07f25c56813c:/# systemctl start ssh
root@07f25c56813c:/# systemctl status ssh
ssh.service - OpenBSD Secure Shell server
    Loaded: loaded (/lib/systemd/system/ssh.service, enabled)
    Active: active (running)
```
Is starts and without any warning. It seems that the `systemd-tmpfiles-setup` currently never starts automatically.

**Comment by gdraheim** [comment]
Actually, systemctl.py will ignore any module like systemd* as it does not want to interfere with a real system daemon. The container is assumed to be prepared enough to run other services which are not from systemd.

And there may be another limitation in that systemctl.py will not start dependencies automatically. The systemctl.py default will simply look for all services that are "enabled" and start them in the correct order.

From my point of view: if some directory from systemd is required that is not present then one should make a workaround in the container setup to prepare them.

**Comment by mvorisek** [comment]
I fixed the tmpfiles issues with:
```
apt-get install -y -qq systemd > /dev/null
wget https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py -O /usr/bin/systemctl_replacement.py
echo -e "#!/bin/bash\n"\
        "systemd-tmpfiles --create --remove\n"\
        "echo calling python \"\$@\"\n"\
        "exec /usr/bin/systemctl_replacement.py \"\$@\"\n"\
        > /usr/bin/systemctl
chmod +x /usr/bin/systemctl /usr/bin/systemctl_replacement.py
```

Now if a new service is installed by Ansible, systemctl start can be called immediatelly. Hope this will help others with the same issue.

Closing this issue as the issues with this program were fixed. Thanks a lot!

**Comment by mvorisek** [comment]
Reopening as never packages uses the `RuntimeDirectory` directory more and more and the solution using `systemd-tmpfiles --create --remove` is not working anymore. Like the `openssh-server` which uses it now starting from Debian Buster release.

The code should be simple, read `RuntimeDirectory` + mode + runtime user/group and create the directory before any management operation on that service.

Can you implement it?
