### ISSUE TITLE
How to run this script

### ISSUE THREAD

**Issue by manulachathurika** [gdraheim/docker-systemctl-replacement#72]
Hi,

Could you please let me know how to run this script. 

[stack@ee3b577b73bd devstack]$ sudo wget https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py -O /usr/local/bin/systemctl
--2019-07-11 09:34:19--  https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.128.133, 151.101.192.133, 151.101.0.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.128.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 203759 (199K) [text/plain]
Saving to: ‘/usr/local/bin/systemctl’

100%[================================================================================================================================================================================>] 203,759     1.18MB/s   in 0.2s   

2019-07-11 09:34:20 (1.18 MB/s) - ‘/usr/local/bin/systemctl’ saved [203759/203759]

[stack@ee3b577b73bd devstack]$ 

Thanks !

**Comment by athena0416** [comment]
I guess you can run it just like use systemctl.
systemctl start xx
  systemctl stop xx
  systemctl status xx
 systemctl reload xx
systemctl is-enabled xx
systemctl enable xx
systemctl disable xx

**Comment by manulachathurika** [comment]
Thanks. Will do it.
