### ISSUE TITLE
Sql server daemon is not getting started

### ISSUE THREAD

**Issue by bansatya** [gdraheim/docker-systemctl-replacement#76]
HI,

I am running a single docker container(ubuntu) within which I am running multiple processes like Nginx, MSSql, java jars etc.
To restart the daemon, I am using systemctl.py script. It executes successfully and starting the Nginx daemon successfully. However, it's not able to start MS-SQL. The command executed without any error but the daemon is not started.

Please refer below:

![image](https://user-images.githubusercontent.com/33546557/65158638-4b627e00-da22-11e9-93b9-51ab6e0bd008.png)

**Comment by gdraheim** [comment]
So it is really ms-sql and not mysql. ;) .... anyway.
1) please show the service descript `systemctl.py cat mssql-server.service`
2) run the systemctl.py with -vvv to get more verbose messages
3) to get debug-logs for the init-process, create /var/log/systemctl.debug.log in the dockerfile

**Comment by gdraheim** [comment]
no response.
