### ISSUE TITLE
Foreground start [feature]

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#8]
This _systemctl_ replacement would be even more useful inside containers if it allows foreground start -- something like

    systemctl start --foreground apache2

to make it suitable for Docker's `ENTRYPOINT` command.

Thank you.

**Comment by gdraheim** [comment]
Isn't the init-loop enough for that?

I am regularly using "systemctl init apache2" which works great, however I have using CMD in the examples. I condider that a core feature of the project.

Best regards, Guido

Am 2. August 2017 06:14:45 MESZ schrieb Dmitry Smirnov <notifications@github.com>:
>This _systemctl_ replacement would be even more useful inside
>containers if it allows foreground start -- something like
>
>    systemctl start --foreground apache2
>
>to make it suitable for Docker's `ENTRYPOINT` command.
>
>Thank you.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gdraheim/docker-systemctl-replacement/issues/8

-- Guido Draheim / +49-1577-1578-077

**Comment by onlyjob** [comment]
Yes that seems to be exactly what I was looking for. Thank you. However I could not find any information on this (undocumented?) feature... Perhaps it is worth mentioning in README as well as in built-in help?

**Comment by gdraheim** [comment]
Actually, it is right there in the documentation.

Have a look at the section "Installation as an init-replacement" of the README.md

**Comment by onlyjob** [comment]
Perhaps insufficiently documented... I actually read it before opening this ticket but could not recognize applicability of this feature. Example like `systemctl init apache2` in the README could be very helpful.

**Comment by gdraheim** [comment]
The example is right there:

> grep -2 " init " README.md 
services shall be run then one can exchange the "default"
command with an explicit start list (and be sure to 
activate the continued execution as an init process):

    /usr/bin/systemctl.py init mongodb myapp

=> feel free to work on the documentation if you like to. ;)

**Comment by gdraheim** [comment]
This one can be closed?

**Comment by onlyjob** [comment]
All good, thanks.
