### ISSUE TITLE
1.4.3424: EnvironmentFile should recognize "%p" Specifier

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#96]
My _app.service_ file contains the following:

````
Environment=JAVA_OPTIONS=-Xmx4000m
EnvironmentFile=-/etc/default/%p
````

`/etc/default/app` contains

```
JAVA_OPTIONS=-Xmx2222m
```

However EnvironmentFile is not loaded and service starts with default `-Xmx4000m` parameter.

With hard-coded file name `EnvironmentFile=-/etc/default/app` works properly.

Please support some basic [Specifiers](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers) (at least `%p`), as per specification. Thanks!

**Comment by gdraheim** [comment]
According to the source code, environmentfile is actually subject to "expand_special".

    def get_env(self, conf):
        env = os.environ.copy()
        for env_part in conf.getlist("Service", "Environment", []):
            for name, value in self.read_env_part(self.expand_special(env_part, conf)):
                env[name] = value # a '$word' is not special here (lazy expansion)
        for env_file in conf.getlist("Service", "EnvironmentFile", []):
            for name, value in self.read_env_file(self.expand_special(env_file, conf)):
                env[name] = self.expand_env(value, env) # but nonlazy expansion here

and expand_special does know about the %p special

    def expand_special(self, cmd, conf = None):
        def get_confs(conf):
            confs={ "%": "%" }
            if not conf:
                return confs
            unit = parse_unit(conf.name())
            confs["N"] = unit.name
            confs["n"] = sh_escape(unit.name)
            confs["P"] = unit.prefix
            confs["p"] = sh_escape(unit.prefix)

So as for your request, the Specifiers are supported.

**Comment by gdraheim** [comment]
Can you provide a testcase that shows the error?

**Comment by onlyjob** [comment]
The original report is literally a test case (it has everything to reproduce the problem). However I did not have a chance to test v1.4.4147 yet. If support for Specifiers was introduced between 1.4.3424 and 1.4.4147 then the problem may have already been solved.

I'll test 1.4.4147 and report.

**Comment by onlyjob** [comment]
Unfortunately even with 1.4.4147 `EnvironmentFile=-/etc/default/%p` does not work.

Data from the environment file is picked up only when service name is hard-coded: `EnvironmentFile=-/etc/default/app`.

**Comment by gdraheim** [comment]
It is still about a testcase to compare it with systemd systemctl.

The service specs that I had used so far were choosing %n for the unit name. What's the purpose of using %p in here? I can only guess that it has to do with some kind of template spec - and tthat has only minimal testing with systemctl.py. I dont use template services in my own usage scenarios.

**Comment by onlyjob** [comment]
> It is still about a testcase to compare it with systemd systemctl.

I don't understand. Of course I have tested against systemd and reported the difference in this very bug report. Moreover, service file that works as expected under systemd fails under _systemctl-replacement_.

I'm not sure if _purpose_ of `%p` is relevant. It is being used exactly as I reported. For `app.service`, `%p` expands as `app` which allows to load corresponding environment file easily.

_I think it would be best to extend support for service files specifiers for greater compliance with specification._

For what it's worth, I'm using service templates but not on this instance. To make things work I had to patch the service file to hard-code the name of the service (which is silly).

IMHO purpose of `%p` is to use less hard-coding when writing service files and minimise chances of mistakes when copy-pasting/reusing portions of service files to create new services.

**Comment by gdraheim** [comment]
I have created a testcase "make real_3270" which shows the special variable expansion of the installed systemd systemctl. In comparison the "make test_3270" using systemctl3.py show some differences. That's where the real bugs are.

I just don't have time to work on it now (develop branch).

**Comment by gdraheim** [comment]
Please check also the 1.5.x branch which is now in master. The expansion of special variables has changed considerably and %p specifier should not be an issue anymore.
