### ISSUE TITLE
Getting access to logs

### ISSUE THREAD

**Issue by krisklau** [gdraheim/docker-systemctl-replacement#99]
Hi, 

I am trying to use the tool as a init-process in a run-time docker-container. 

In my current test-setup I have gotten my processes to start (directly started the services with `systemctl --init start <> <>`). 

In systemd I have access to `journald`, but that seems to be empty even if I start the `systemd-journald` service. 

How do I access the output logs from the services?

Kristian

**Comment by gdraheim** [comment]
Have a look into /var/log/journal - systemd puts the files there as well but with systemctl.py they are named after the service that they are attached to.

If you run systemctl.py as pid1 then "docker log" should give you all output. It depends a bit on the version that you use.

A kind of "journal" lookalike, perhaps just "systemctl.py log", would be nice but with the direct access to the log files I did not have a use for it.

**Comment by krisklau** [comment]
Thank you for the swift answer, found the logs at the location you described. 

I like the idea of a journalctl lookalike. Potentially could be a standalone companion-tool, journalctl.py, which reads the logs from systemctl.py.

**Comment by cardin** [comment]
A really quick hack of a Python Journalctl:
https://github.com/cardin/docker-systemctl-replacement/blob/master/files/docker/journalctl3.py

Doesn't check input; only supports `-f`, `-n`, and `-u`; has none of the time-related capabilities like `-b` or `--since`.

**Comment by gdraheim** [comment]
@cardin - thanks a lot for the idea. I did the implementation a bit different by implementing "systemctl log <service>" where the journalctl3.py example is a thin wrapper. Both the wrapper and the log-command do implement the options as you proposed.
